let listDescriptions = [
  [],
  [
    //system
    "Monitors, brightness, nightlight, display profile",
    "Volume levels, output, input, sound devices",
    "Alert from app and system, do not disturb",
    "Reduce distractions",
    "Sleep, battery usage, battery saver",
    "Storage space, drives, configuration rules",
    "Discoverability, received files location",
    "Snap windows, desktops,task switching",
    "These settings are intended for development use only",
    "Activation state, subscriptions, product key",
    "Recommended troubleshooters, preferences, history",
    "Reset, advance startup, go back",
    "Permissions, pairing PIN, discoverability",
    "Remote Desktop users, connection permissions",
    "Remove and manage system components that are preinstalled on Windows",
    "Cut and copy history, sync, clear",
    "About specifications, rename PC, specfications",
  ],

  [
    //bluetooth
    "Mouse, keyboard, pen, audio, displays and docks, other devices",
    "Preferences, troubleshoot",
    "Instantly access your mobile device from your PC",
    "Connected cameras, default image settings",
    "Buttons, mouse pointer speed, scrolling",
    "Taps,gestures, scrolling, zooming",
    "Right-handed or left-handed, pen button shortcuts, handwriting",
    "Defaults for removable drives and memory cards",
    "Notification, USB battery saver",
  ],
  [
    //netwrok
    "Connect, manage known networks, metered network",
    "Authentication, IP and DNS settings, metered network",
    "Add, connect, manage",
    "Share your internet connection",
    "Stop wireless communication",
    "Proxy server for Wi-Fi and Ethernet connections",
    "Set up a dial-up internet connection",
    "View all network adapters, network reset",
  ],
  [
    //personalization
    "Background image, color, slideshow",
    "Accent color, transparency effects, color theme",
    "Install, create, manage",
    "Connect devices, effects, add settings",
    "Lock screen images, apps, annimations",
    "Touch keyboard, voice typing, emoji and more, input methon editor",
    "Recent apps and items, folders",
    "Taskbar behaviors, system pins",
    "Install, manage",
    "Select all the ways you plan to use your device to get personalized tips, ads, and recommendations within Microsoft experiences.",
  ],
  [],
  [],
  [],
  [],
  [],
  [],
  [],
];
